%% Introduction
% For each note in piano_recordings, we should have an associated section
% dedicated to analyzing the spectrum over 5 seconds. We will visualize
% the spectrogram for each recording and map the frequency content in bins
% of 20 Hz. Each 'bin' will have an associated best fit function that will be
% its carrier which will be implemented on the device. We will also
% visualize visualize the FFT of each recording to pick out what
% frequencies are present in each 'bin'. These frequencies will be
% generated by the device and multiplied by the carrier functions which 
% represent the transience of the note being played.


% lowest note is a C3, f = 130.81
% frequency table here: https://www.phys.unsw.edu.au/jw/notes.html


%% Choosing file and visualizations

% read in audio sample
[x,Fs] = audioread(fullfile(pwd, "piano_recordings", "E.wav"));

% calculate input window.
T = 0.25;
win = Fs*T;

% calculate spectrogram
[s,f,t] = spectrogram(x, win, [], [], Fs);

% display spectrogram with hertz
figure
spectrogram(x, win, [], [], Fs,'yaxis')
ylim([0, 0.7])

% display frequencies at 1 second into audio sample
figure
plot(f, abs(s(:,find(t>1, 1))))
xlim([0,1000])

% Constants for spectral decomposition
BIN_FREQ = 20; % 10 Hz frequency bins
BIN_FREQ_INDEX = round(BIN_FREQ / (f(2) - f(1)));
NUM_HARMONICS = 5;
THRESHOLD_LOCAL_MAX_POWER = 1e4;

% Finding audio power from frequency spectrum
audio_power = abs(s).^2; % Using magnitude of s to find maximums
start_time_index = find(sum(audio_power, 1) > max(sum(audio_power, 1)) * 0.01, 1);
last_time_index = find(sum(audio_power, 1) > max(sum(audio_power, 1)), 1, 'last');

smoothed_audio_power = smoothdata(audio_power, 2, 'movmean', BIN_FREQ_INDEX);
max_power_index = find(islocalmax(sum(smoothed_audio_power, 1)), 1);

% Find harmonic frequencies and bin starts and ends
local_max_index = find(islocalmax(smoothed_audio_power(:,max_power_index), 'MinProminence', THRESHOLD_LOCAL_MAX_POWER), 1);
local_max_indices = local_max_index * (1:NUM_HARMONICS);
bin_starts = max(local_max_indices - floor((BIN_FREQ_INDEX/2)), zeros(size(local_max_indices)) + 1);
bin_ends = min(local_max_indices + ceil((BIN_FREQ_INDEX/2 - 1)), zeros(size(local_max_indices)) + length(f));

% Find powers in harmonics
harmonics_powers = zeros(NUM_HARMONICS, length(t));

for hrmnc = 1:length(local_max_indices)
    harmonics_powers(hrmnc, :) = sum(audio_power(bin_starts(hrmnc):bin_ends(hrmnc), :), 1);
end

%% Plots for audio power and harmonic powers
figure
hold on
plot(t(start_time_index:last_time_index), sum(audio_power(:, start_time_index:last_time_index), 1))
plot(t(start_time_index:last_time_index), sum(harmonics_powers(:, start_time_index:last_time_index), 1))
legend("Original Spectral Powers", "Decomposed Spectral Powers")

figure
hrmnc_num = 1;
plot(t(start_time_index:end), harmonics_powers(hrmnc_num, start_time_index:end))

%% Fitting
harmonics_magnitudes = sqrt(harmonics_powers);

% Initial attempt at using linear regression, but result was unoptimal
% % Model to fit to is s(t) = alpha * t^(beta) * e^(-gamma * t), or
% % ln(s) = ln(alpha) + beta * ln(t) - gamma * t
% harmonics_parameters = zeros(NUM_HARMONICS, 3);
% 
% for hrmnc = 1:length(local_max_indices)
%     A = [ones(length(t(start_time_index:last_time_index)), 1), log(t(start_time_index:last_time_index) - t(start_time_index-1))', -(t(start_time_index:last_time_index) - t(start_time_index-1))'];
%     b = log(harmonics_magnitudes(hrmnc, start_time_index:last_time_index))';
%     harmonics_parameters(hrmnc, :) = reshape(lsqr(A, b, 1e-6, 1000), [1, 3]);
%     harmonics_parameters(hrmnc, 1) = exp(harmonics_parameters(hrmnc, 1));
% end

% % Second attempt to use linear regression
% % s(t) = alpha * (t-t0)^(beta) * e^(-gamma * (t-t0)) + delta
% % Order of params is: alpha, beta, gamma, delta, t0
% % t0 is commented out for now, set to 0 since can be approximated to be so
% harmonics_parameters = zeros(NUM_HARMONICS, 4);
% harmonics_parameters(:, 1) = 1000;
% harmonics_parameters(:, 2) = 0.5;
% harmonics_parameters(:, 3) = 1;
% harmonics_parameters(:, 4) = 0.1;
% % harmonics_parameters(:, 5) = 0.1;
% 
% % model_func = @(b,x)(b(1)*(x-b(5)).^b(2).*exp(-b(3)*(x-b(5)))+b(4));
% model_func = @(b,x)(b(1)*x.^b(2).*exp(-b(3)*x)+b(4));
% 
% for hrmnc = 1:length(local_max_indices)
%     X = (t(start_time_index:last_time_index))';
%     y = harmonics_magnitudes(hrmnc, start_time_index:last_time_index)';
%     model_output = fitnlm(X, y, model_func, harmonics_parameters(hrmnc,:), Options=statset("DerivStep", 0.5, "MaxIter",10000));
%     % harmonics_parameters(hrmnc, :) = reshape(model_output.Coefficients.Estimate, [1, 5]);
%     harmonics_parameters(hrmnc, :) = reshape(model_output.Coefficients.Estimate, [1, 4]);
% end

% Simplified model -- linear ramp to max then decay
% Parameters are: time to reach max, actual max value, and then for the
% decay model I use the following after looking at the decay curves:
% e^(-ax^b), where a and b are the parameters
% This allows to use log(-log(output)) as the b and ones along with log(t)
% as the A matrix
harmonics_parameters = ones(NUM_HARMONICS, 4);
[local_max_values_harmonics, local_max_time_indices] = max(harmonics_magnitudes, [], 2);
local_max_values_harmonics
local_max_time_indices = local_max_time_indices - start_time_index;
local_max_times = local_max_time_indices * T/2;
harmonics_parameters(:, 1) = local_max_times;
harmonics_parameters(:, 2) = local_max_values_harmonics;

for hrmnc = 1:length(local_max_indices)
    decaying_harmonic = harmonics_magnitudes(hrmnc, (local_max_time_indices(hrmnc, 1) + start_time_index):end) / ...
        harmonics_magnitudes(hrmnc, local_max_time_indices(hrmnc, 1) + start_time_index);
    A = [ones(length(decaying_harmonic), 1), ...
        log(t((local_max_time_indices(hrmnc, 1) + start_time_index):end) - t(local_max_time_indices(hrmnc, 1) + start_time_index))'];
    A = A(2:end, :);
    b = log(-log(decaying_harmonic(2:end)))';
    harmonics_parameters(hrmnc, 3:4) = reshape(lsqr(A, b, 1e-6, 1000), [1, 2]);
    harmonics_parameters(hrmnc, 3) = exp(harmonics_parameters(hrmnc, 3));

    figure
    hold on
    plot(log(decaying_harmonic))
    plot(-harmonics_parameters(hrmnc, 3) * (t((local_max_time_indices(hrmnc, 1) + start_time_index):end) - t(local_max_time_indices(hrmnc, 1) + start_time_index)).^harmonics_parameters(hrmnc, 4));
    hold off
    title("Matching Decaying Harmonics with Theoretical")
end

function output=model_func(params, t)
    output=zeros(size(t));
    for tind = 1:length(t)
        if t(tind) < params(1)
            output(tind) = (params(2) / params(1)) * t(tind);
        else
            output(tind) = params(2) * exp(-params(3) * ((t(tind)-params(1))^params(4)));
        end
    end
end

%% Plots for modeled curve and parameters
figure
hold on
hrmnc_num = 1;
plot(t(start_time_index:end), harmonics_magnitudes(hrmnc_num, start_time_index:end))
% Initial attempt: plot(t(start_time_index:end), harmonics_parameters(hrmnc_num, 1) * (t(start_time_index:end)-t(start_time_index-1)).^(harmonics_parameters(hrmnc_num, 2)) .* exp(-harmonics_parameters(hrmnc_num, 3) * (t(start_time_index:end)-t(start_time_index-1))))
% Second and third attempts:
plot(t(start_time_index:end), model_func(harmonics_parameters(hrmnc_num, :), t(start_time_index:end)-t(start_time_index)))
hold off
legend Actual Model

frequencies_to_use = f(local_max_indices);
disp("freqs to use")
disp(frequencies_to_use)