%% Introduction
% For each note in piano_recordings, we should have an associated section
% dedicated to analyzing the spectrum over 5 seconds. We will visualize
% the spectrogram for each recording and map the frequency content in bins
% of 20 Hz. Each 'bin' will have an associated best fit function that will be
% its carrier which will be implemented on the device. We will also
% visualize visualize the FFT of each recording to pick out what
% frequencies are present in each 'bin'. These frequencies will be
% generated by the device and multiplied by the carrier functions which 
% represent the transience of the note being played.


%% Example

% read in audio sample
[x,Fs] = audioread("piano_recordings\C.wav");

% calculate input window.
T = 0.25;
win = Fs*T;

% calculate spectrogram
[s,f,t] = spectrogram(x, win, [], [], Fs);

% display spectrogram with hertz
figure(1)
spectrogram(x, win, [], [], Fs,'yaxis')
ylim([0, 0.7])

% display frequencies at 1 second into audio sample
figure(2)
plot(f, abs(s(:,find(t>1, 1))))
xlim([0,1000])